
import type { Metadata } from "next";
import { Athiti, Ojuju } from "next/font/google"
import "./custom.scss";

const inter = Athiti({ weight: "500", subsets:["latin"] });
const ojuju = Ojuju({ weight: "500", subsets:["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
